import React from 'react';
import { Download, Play, Pause, Trash2, History, Pencil, X, Check, Layers } from 'lucide-react';
import { clsx } from 'clsx';
import type { HistoryItem, useAudioEditorHistory } from '../../hooks/useAudioEditorHistory';

interface TauntHistoryListProps {
    historyState: ReturnType<typeof useAudioEditorHistory>;
    handleReloadIntoEditor: (item: HistoryItem) => void;
}

export const TauntHistoryList: React.FC<TauntHistoryListProps> = ({ historyState, handleReloadIntoEditor }) => {
    const {
        history, isPruning, editingId, editName, setEditName, handleSaveRename, setEditingId,
        handlePreviewHistory, playingId, handleDownloadHistoryItem, handleDeleteHistoryItem,
        handlePruneCorruptFiles,
    } = historyState;
    const corruptHistoryCount = history.filter(h => h.blob.size < 6000).length;

    return (
        <div className="mt-10 pt-6 border-t border-white/10 space-y-4">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-white">
                    <History className="w-4 h-4 text-[#ff6600]" />
                    <h3 className="text-base font-bold">Recent Audio Taunts ({history.length})</h3>
                </div>

                {corruptHistoryCount > 0 && (
                    <button
                        onClick={handlePruneCorruptFiles}
                        disabled={isPruning}
                        className="px-3 py-1 bg-red-500/20 hover:bg-red-500/30 border border-red-500/40 text-red-300 text-xs rounded-lg flex items-center gap-1.5 transition-all"
                        title="Removes empty/0-sample cuts generated by previous sessions"
                    >
                        <Trash2 className="w-3.5 h-3.5 text-red-400" />
                        <span>Prune {corruptHistoryCount} Empty Taunts</span>
                    </button>
                )}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {history.map((item) => {
                    const isCorrupt = item.blob.size < 6000;
                    return (
                        <div 
                            key={item.id} 
                            className={clsx(
                                "border rounded-xl p-3 flex items-center justify-between group transition-all",
                                isCorrupt 
                                    ? "bg-red-950/20 border-red-500/20" 
                                    : "bg-black/40 border-white/5 hover:border-white/15"
                            )}
                        >
                            <div className="flex flex-col overflow-hidden flex-grow mr-3">
                                {editingId === item.id ? (
                                    <div className="flex items-center space-x-2">
                                        <input
                                            type="text"
                                            value={editName}
                                            onChange={(e) => setEditName(e.target.value)}
                                            className="bg-black border border-[#ff6600] rounded px-2 py-1 text-xs text-white w-full focus:outline-none"
                                            autoFocus
                                            onKeyDown={(e) => {
                                                if (e.key === 'Enter') handleSaveRename(item.id);
                                                if (e.key === 'Escape') setEditingId(null);
                                            }}
                                        />
                                        <button onClick={() => handleSaveRename(item.id)} className="text-green-400 p-1"><Check className="w-4 h-4" /></button>
                                        <button onClick={() => setEditingId(null)} className="text-red-400 p-1"><X className="w-4 h-4" /></button>
                                    </div>
                                ) : (
                                    <>
                                        <div className="flex items-center gap-2">
                                            <span className="text-xs font-bold text-gray-200 truncate" title={item.name}>
                                                {item.name}
                                            </span>
                                            {isCorrupt && (
                                                <span className="px-1.5 rounded text-[9px] bg-red-500/20 text-red-400 font-bold border border-red-500/30">
                                                    Empty / 0 samples
                                                </span>
                                            )}
                                        </div>
                                        <div className="flex space-x-3 text-[11px] text-gray-500 mt-0.5">
                                            <span>{new Date(item.date).toLocaleDateString()}</span>
                                            <span>{(item.blob.size / 1024).toFixed(1)} kB</span>
                                        </div>
                                    </>
                                )}
                            </div>

                            <div className="flex items-center gap-1 opacity-85 group-hover:opacity-100 transition-opacity">
                                <button
                                    onClick={() => handlePreviewHistory(item)}
                                    className={clsx(
                                        "p-1.5 rounded-lg hover:bg-white/10 transition-colors",
                                        playingId === item.id ? "text-green-400 bg-green-500/10" : "text-gray-400"
                                    )}
                                    title="Preview Taunt"
                                >
                                    {playingId === item.id ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
                                </button>

                                {/* Reload into Workstation to re-trim */}
                                <button
                                    onClick={() => handleReloadIntoEditor(item)}
                                    className="p-1.5 hover:bg-white/10 rounded-lg text-[#ff6600]"
                                    title="Load back into Waveform Editor"
                                >
                                    <Layers className="w-4 h-4" />
                                </button>

                                <button
                                    onClick={() => {
                                        setEditingId(item.id);
                                        setEditName(item.name);
                                    }}
                                    className="p-1.5 hover:bg-white/10 rounded-lg text-yellow-400"
                                    title="Rename"
                                >
                                    <Pencil className="w-4 h-4" />
                                </button>

                                <button
                                    onClick={() => handleDownloadHistoryItem(item)}
                                    className="p-1.5 hover:bg-white/10 rounded-lg text-blue-400"
                                    title="Download"
                                >
                                    <Download className="w-4 h-4" />
                                </button>

                                <button
                                    onClick={() => handleDeleteHistoryItem(item.id)}
                                    className="p-1.5 hover:bg-white/10 rounded-lg text-red-400"
                                    title="Delete"
                                >
                                    <Trash2 className="w-4 h-4" />
                                </button>
                            </div>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};
